spring:
  mvc:
    static-path-pattern: /**
  resources:
    add-mappings: true
    cache:
      period: 3600
      cachecontrol:
        max-age: 1d
  sbp:
    runtime-mode: development
#    runtime-mode: deployment
    plugins-root: plugins
    enabled: true
    auto-start-plugin: true
    classes-directories:
      - "target/classes"
    controller:
      base-path: "/sbp/admin"
  datasource:
    url: jdbc:mysql://localhost:3306/crm?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: annihilation
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  thymeleaf:
    mode: HTML
    cache: false
  flyway:
    enabled: false
  main:
    banner-mode: off



org:
  hibernate:
    envers:
      audit_table_suffix=_audit
      default_schema=crm

images:
  file:
    path: "/Users/zhmaksat/Documents/Zoom"
barrier:
  open:
    disabled: true