Smartparking monolithic application

== Key components
* https://spring.io/projects/spring-boot
* https://github.com/pf4j/pf4j-spring
* https://github.com/hank-cp/sbp

== How to get started

You need java version 11, maven 3.X.X or later, Mysql database with scheme 'crm' - for development and 'new_parking' for production

==== Default application start in development mode

First, build plugin application:
----
mvn clean package
----

==== Run main jar
----
java -jar spt-root-0.0.1-SNAPSHOT-standalone.jar
----

==== Application start in production mode inside docker container

For production master branch of https://github.com/Parqour-Inc/parking_management_software is used

Firstly, build docker image by task spt-app-prod-image inside jenkins located at http://10.66.5.6:8080/

=== If application about to run the for first time

All compose yml files located inside docker-prod/compose folder

Inside new server create new_parking folder:
----
mkdir new_parking && cd new_parking
----
also create nginx folder for nginx configuration
----
mkdir nginx
----

Copy suitable yml from docker-prod/compose of git to remote server
----
cd docker-prod/compose
scp {suitable}.yml {user}@{server_ip}:~/new_parking/.
----
Next, copy enabled.txt from docker-prod to remote server
----
cd ..
scp enabled.txt {user}@{server_ip}:~/new_parking/.
----
and nginx.conf from docker-prod/nginx to remote server
----
cd nginx
scp nginx.cnf {user}@{server_ip}:~/new_parking/nginx/.
----

Then start docker containers use command
----
docker-compose -f {suitable}.yml up -d
----

=== If application is updating

Then change only doc.smartparking.kz/spt-app:x version to doc.smartparking.kz/spt-app:y version, where y is new built version of jenkins task.

