FROM anapsix/alpine-java:8_jdk
LABEL maintainer="kairzhan79@gmail.com"

WORKDIR /usr/local/
COPY spt-root-0.0.1-SNAPSHOT-standalone.jar /usr/local/
CMD java -jar spt-root-0.0.1-SNAPSHOT-standalone.jar

EXPOSE 8888
