spring:
  mvc:
    static-path-pattern: /**
  resources:
    add-mappings: true
    cache:
      period: 3600
  sbp:
    runtime-mode: deployment
    plugins-root: plugins
    enabled: true
    auto-start-plugin: true
    controller:
      base-path: "/sbp/admin"
    plugin-properties:
      spring:
        datasource:
          url: jdbc:mysql://10.66.5.6:3307/parking?allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: root
        jpa:
          hibernate:
            ddl-auto: update
          database-platform: org.hibernate.dialect.MySQL55Dialect
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://10.66.5.6:3307/parking?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  thymeleaf:
    mode: HTML
    cache: false
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
org:
  hibernate:
    envers:
      audit_table_suffix: _audit
      default_schema: parking

images:
  file:
    path: "/Users/zhmaksat/Documents/Zoom"
barrier:
  open:
    disabled: false
car:
  movement:
    simulate: false
status:
  check:
    fixedDelay: 250
parking:
  cameras:
    camera-1: 10.66.22.20
    camera-2: 10.66.22.23