spring:
  mvc:
    static-path-pattern: /**
  resources:
    add-mappings: true
    cache:
      period: 3600
  sbp:
    runtime-mode: deployment
    plugins-root: plugins
    enabled: true
    auto-start-plugin: true
    controller:
      base-path: "/sbp/admin"
    plugin-properties:
      spring:
        datasource:
          url: jdbc:mysql://10.66.5.6:3307/parking?allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: root
        jpa:
          hibernate:
            ddl-auto: update
          database-platform: org.hibernate.dialect.MySQL55Dialect
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL55Dialect
              jdbc:
                time_zone: UTC
  datasource:
    url: jdbc:mysql://10.66.5.6:3307/parking?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        jdbc:
          time_zone: UTC
  thymeleaf:
    mode: HTML
    cache: false
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: parqour.smartparking@gmail.com
    password: aqaxhlmflyfvujnr
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
org:
  hibernate:
    envers:
      audit_table_suffix: _audit
      default_schema: parking
server:
  servlet:
    session:
      timeout: 57600 # 5 hours lasts session
images:
  file:
    path: "/Users/zhmaksat/Documents/Zoom"
barrier:
  open:
    disabled: false
car:
  movement:
    simulate: false
status:
  check:
    fixedDelay: 250
booking:
  halapark:
    check: false # включить проверку booking для разных операторов.
    tokenUrl: http://halapark.calltekky.com/api/auth/getToken
    postUrl: http://halapark.calltekky.com/api/auth/getBookingByParquorcameras
zero:
  touch:
    rahmet:
      check: false
      tokenUrl: https://gateway.chocodev.kz/auth/token
      clientId: 35000006
      clientPassword: f5ae4d63b60d9845f95a69bc4240806810338b940a2d0ee8211270a303be66e1
      postUrl: gateway.chocodev.kz/payments/v1/smartparking/pay
parking:
  has:
    access:
      unknown:
        cases: false # Выпускать все авто где вьезд не найден
telegram:
  bot:
    external:
      enabled: false