services:
  spt-app:
    image: spt-app:latest
    restart: always
    environment:
      - "TZ=Asia/Almaty"
    volumes:
      - /var/www/parking/storage/new_parking:/files/pictures:rw
    logging:
      options:
        max-size: 50m
    networks:
      - parking-net
  nginx:
    image: nginx:1.14.0
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - "/var/www/parking/storage/new_parking:/files"
    links:
      - spt-app
    logging:
      options:
        max-size: 50m
    networks:
      - parking-net
  imgproxy:
    image: darthsim/imgproxy
    ports:
      - "9980:8080"
    environment:
      - "IMGPROXY_LOCAL_FILESYSTEM_ROOT=/tmp/snapshot"
    volumes:
      - "/var/www/parking/storage/new_parking:/tmp/snapshot"
networks:
  parking-net:
    external: true
version: '2.1'