services:
  nginx:
      image: nginx:1.21.4
      restart: always
      ports:
          - "9991:80"
      volumes:
        - "./nginx:/etc/nginx/conf.d"
        - "/var/www/parking/storage/new_parking:/files"
version: '2.1'