services:
  spt-app:
    image: spt-app:latest
    restart: always
    environment:
      - "TZ=Asia/Almaty"
    volumes:
      - /var/www/parking/storage/new_parking:/files/pictures:rw
    logging:
      options:
        max-size: 50m
    networks:
      - parking-net
networks:
  parking-net:
    external: true
version: '2.1'