spring:
  mvc:
    static-path-pattern: /**
  resources:
    add-mappings: true
    cache:
      period: 3600
  sbp:
    runtime-mode: deployment
    plugins-root: plugins
    enabled: true
    auto-start-plugin: true
    controller:
      base-path: "/sbp/admin"
    plugin-properties:
      spring:
        datasource:
          url: jdbc:mysql://db/new_parking?allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: root
        jpa:
          hibernate:
            ddl-auto: update
          database-platform: org.hibernate.dialect.MySQL55Dialect
          properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://db/new_parking?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
#    open-in-view: false TODO: enable in production to reduce database connect on every web page call
  thymeleaf:
    mode: HTML
    cache: false
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  tomcat:
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 57600 # 16 hours lasts session
org:
  hibernate:
    envers:
      audit_table_suffix: _audit
      default_schema: new_parking
images:
  file:
    path: "/files/pictures"
barrier:
  open:
    disabled: false
car:
  movement:
    simulate: false
status:
  check:
    fixedDelay: 250
whitelist:
  group:
    show:
      advanced: false
booking:
  halapark:
    check: false # включить проверку booking для разных операторов.
    tokenUrl: http://halapark.calltekky.com/api/auth/getToken
    postUrl: http://halapark.calltekky.com/api/auth/getBookingByParquorcameras